default: &default
  adapter: postgresql
  encoding: unicode
  # 環境変数 DATABASE_HOST があればそれを使い、なければ 'db' を使う
  host: <%= ENV.fetch("DATABASE_HOST") { "db" } %>
  user: postgres
  # 環境変数 DATABASE_PASSWORD があればそれを使い、なければ 'password' を使う
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "password" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: todo_roulette_development

test:
  <<: *default
  database: todo_roulette_test

production:
  <<: *default
  # 本番（Render）用
  url: <%= ENV['DATABASE_URL'] %>