default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password

development:
  <<: *default
  database: todo_roulette_development
  # WSLからDockerのDBに繋ぐために localhost を指定
  host: localhost

test:
  <<: *default
  database: todo_roulette_test
  host: localhost

production:
  <<: *default
  # Render本番環境では DATABASE_URL 環境変数から自動接続されるため
  # 個別のDB名やパスワードの指定は不要です
  url: <%= ENV['DATABASE_URL'] %>
